### ISSUE TITLE
Hello :)

### ISSUE THREAD

**Issue by JSettler** [Layheng-Hok/Jungle-Chess#1]
Hello Layheng-Hok, i'm an enthusiastic player of this great boardgame Dou Shou Qi!

Would you like to join our Discord?
https://discord.gg/257jDH3nmn

Our goal is to build an international community around this beautiful game, starting with a discord server. We have already collected lots of resources and weblinks and posted these in our server for anyone to use.
And our discord is bi-lingual: it has areas for english and chinese speakers.
(But its main language is english, to attract a worldwide community.)

Kind regards, JSettler (aka 'paws' in discord)

**Comment by Layheng-Hok** [comment]
Thanks for your interest! I've already joined your Discord server.

**Comment by Layheng-Hok** [comment]
Thanks for your interest! I've already joined your Discord server.
